### ISSUE TITLE
[Bug] `NPM Start` is Failing

### ISSUE THREAD

**Issue by IamManchanda** [zurb/building-blocks#115]
The build is failing and server can't be started 

As a check .... i started foundation sites and its working properly 

Poke @kball @rafibomb for the bug fix

Here is the errors log

```bash
0 info it worked if it ends with ok
1 verbose cli [ '/usr/local/bin/node', '/usr/local/bin/npm', 'start' ]
2 info using npm@4.2.0
3 info using node@v7.9.0
4 verbose run-script [ 'prestart', 'start', 'poststart' ]
5 info lifecycle foundation-building-blocks@1.0.0~prestart: foundation-building-blocks@1.0.0
6 silly lifecycle foundation-building-blocks@1.0.0~prestart: no script for prestart, continuing
7 info lifecycle foundation-building-blocks@1.0.0~start: foundation-building-blocks@1.0.0
8 verbose lifecycle foundation-building-blocks@1.0.0~start: unsafe-perm in lifecycle true
9 verbose lifecycle foundation-building-blocks@1.0.0~start: PATH: /usr/local/lib/node_modules/npm/bin/node-gyp-bin:/opt/lampp/htdocs/zurb/fork/building-blocks/node_modules/.bin:/usr/local/heroku/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/opt/lampp/bin:~/.composer/vendor/bin:/usr/lib/jvm/java-8-oracle/bin:/usr/lib/jvm/java-8-oracle/db/bin:/usr/lib/jvm/java-8-oracle/jre/bin:/home/harman/git-apps/hub-linux/bin/:/home/harman/.config/composer/vendor/bin
10 verbose lifecycle foundation-building-blocks@1.0.0~start: CWD: /opt/lampp/htdocs/zurb/fork/building-blocks
11 silly lifecycle foundation-building-blocks@1.0.0~start: Args: [ '-c', 'gulp bb' ]
12 silly lifecycle foundation-building-blocks@1.0.0~start: Returned: code: 1  signal: null
13 info lifecycle foundation-building-blocks@1.0.0~start: Failed to exec start script
14 verbose stack Error: foundation-building-blocks@1.0.0 start: `gulp bb`
14 verbose stack Exit status 1
14 verbose stack     at EventEmitter.<anonymous> (/usr/local/lib/node_modules/npm/lib/utils/lifecycle.js:279:16)
14 verbose stack     at emitTwo (events.js:106:13)
14 verbose stack     at EventEmitter.emit (events.js:194:7)
14 verbose stack     at ChildProcess.<anonymous> (/usr/local/lib/node_modules/npm/lib/utils/spawn.js:40:14)
14 verbose stack     at emitTwo (events.js:106:13)
14 verbose stack     at ChildProcess.emit (events.js:194:7)
14 verbose stack     at maybeClose (internal/child_process.js:899:16)
14 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)
15 verbose pkgid foundation-building-blocks@1.0.0
16 verbose cwd /opt/lampp/htdocs/zurb/fork/building-blocks
17 error Linux 4.4.0-66-generic
18 error argv "/usr/local/bin/node" "/usr/local/bin/npm" "start"
19 error node v7.9.0
20 error npm  v4.2.0
21 error code ELIFECYCLE
22 error errno 1
23 error foundation-building-blocks@1.0.0 start: `gulp bb`
23 error Exit status 1
24 error Failed at the foundation-building-blocks@1.0.0 start script 'gulp bb'.
24 error Make sure you have the latest version of node.js and npm installed.
24 error If you do, this is most likely a problem with the foundation-building-blocks package,
24 error not with npm itself.
24 error Tell the author that this fails on your system:
24 error     gulp bb
24 error You can get information on how to open an issue for this project with:
24 error     npm bugs foundation-building-blocks
24 error Or if that isn't available, you can get their info via:
24 error     npm owner ls foundation-building-blocks
24 error There is likely additional logging output above.
25 verbose exit [ 1, true ]

```

**Comment by kball** [comment]
I'm not seeing the failure... could be the node version (we've been recommending 6 series, not 7 series), or something else... is there any more log that you can share? Not seeing much in this stack trace.

Also have you rerun npm install since pulling? There might be a package difference

**Comment by IamManchanda** [comment]
Yup NPM Install and chmod 777 did the trick! 
Closing this ..... thanks @kball
