### ISSUE TITLE
foundation Building Block Kits - Install Error

### ISSUE THREAD

**Issue by QamarS** [zurb/building-blocks#250]
C:\Users\556383\ATLAS>foundation -v
Foundation CLI version 2.2.3

But when I try to run "foundation kits install blog", I am seeing an error -
C:\Users\556383\ATLAS>foundation kits install blog
error fetching file /building-blocks/data/kits.json
undefined:1

SyntaxError: Unexpected end of JSON input
    at Object.parse (native)
    at C:\Users\556383\AppData\Roaming\npm\node_modules\foundation-cli\lib\commands\kits.js:41:21
    at IncomingMessage.<anonymous> (C:\Users\556383\AppData\Roaming\npm\node_modules\foundation-cli\lib\util\fetch-url.js:21:9)
    at emitNone (events.js:91:20)
    at IncomingMessage.emit (events.js:185:7)
    at endReadableNT (_stream_readable.js:974:12)
    at _combinedTickCallback (internal/process/next_tick.js:80:11)
    at process._tickCallback (internal/process/next_tick.js:104:9)

C:\Users\556383\ATLAS>

C:\Users\556383\ATLAS>foundation kits

Usage:
  foundation kits list
  foundation kits install <kits>

List available building block kits, or install them

C:\Users\556383\ATLAS>foundation kits list
error fetching file /building-blocks/data/kits.json
undefined:1

SyntaxError: Unexpected end of JSON input
    at Object.parse (native)
    at C:\Users\556383\AppData\Roaming\npm\node_modules\foundation-cli\lib\commands\kits.js:41:21
    at IncomingMessage.<anonymous> (C:\Users\556383\AppData\Roaming\npm\node_modules\foundation-cli\lib\util\fetch-url.js:21:9)
    at emitNone (events.js:91:20)
    at IncomingMessage.emit (events.js:185:7)
    at endReadableNT (_stream_readable.js:974:12)
    at _combinedTickCallback (internal/process/next_tick.js:80:11)
    at process._tickCallback (internal/process/next_tick.js:104:9)

C:\Users\556383\ATLAS>

Please help me.
Sharique

**Comment by bxmas13** [comment]
I'm having the same issue with:
foundation kits list
foundation kits install
foundation blocks list
foundation blocks install

**ERROR:**
  C:\xampp\htdocs\server.website123.com\htdocs\autoship_admin2> foundation kits install
error fetching file /building-blocks/data/kits.json
undefined:1



SyntaxError: Unexpected end of JSON input
    at Object.parse (native)
    at C:\Users\MYUSERNAME\AppData\Roaming\npm\node_modules\foundation-cli\lib\commands\kits.js:41:21
    at IncomingMessage.<anonymous> (C:\Users\MYUSERNAME\AppData\Roaming\npm\node_modules\foundation-cli\lib\util\fetch-url.js:21:9)
    at emitNone (events.js:91:20)
    at IncomingMessage.emit (events.js:185:7)
    at endReadableNT (_stream_readable.js:974:12)
    at _combinedTickCallback (internal/process/next_tick.js:74:11)
    at process._tickCallback (internal/process/next_tick.js:98:9)

**Comment by bxmas13** [comment]
I found the problem. The code in the fetch-url function was pointing to 'http:', which would cause an error when foundation redirected(301) to 'https:'.

Here is how I fixed it:
1. Edit C:/Users/YOURUSERNAME/AppData/Roaming/npm/node_modules/foundation-cli/lib/util/fetch-url.js

Change
`var http = require('http');`
to 
`var http = require('https');`

Blocks and kits should now list and install from the CLI

**Comment by fjluartes** [comment]
I'm also encountering this error on the following commands:

foundation kits list
foundation kits install
foundation blocks list
foundation blocks install

Here is my error message:

error fetching file /building-blocks/data/building-blocks.json
undefined:1



SyntaxError: Unexpected end of JSON input
    at JSON.parse (<anonymous>)
    at C:\Users\Administrator\AppData\Roaming\npm\node_modules\foundation-cli\lib\commands\blocks.js:28:23
    at IncomingMessage.<anonymous> (C:\Users\Administrator\AppData\Roaming\npm\node_modules\foundation-cli\lib\util\fetch-url.js:21:9)
    at emitNone (events.js:111:20)
    at IncomingMessage.emit (events.js:208:7)
    at endReadableNT (_stream_readable.js:1056:12)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
    at process._tickCallback (internal/process/next_tick.js:180:9)


I checked the fetch-url.js and the https is already fixed by I'm still encountering the error. 

Here is the fetch-url part:
```javascript
var https = require('https');

module.exports = function fetchUrl(host, path, done) {
  var options = {
    host: host,
    path: path
  };
  var callback = function(response) {
    var data = [];
    response.on('data', function(chunk) {
      data.push(chunk);
    });
    response.on('end', function() {
      if(response.statusCode === 200) {
        var buffer = Buffer.concat(data);
        done(buffer);
      } else if (response.statusCode == 404) {
        done('');
      } else {
        console.log('error fetching file', path);
        done('');
      }
    });
  };
  https.request(options, callback).end();
}
```
